HansungCapstoneDesign/Capstone-Design

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardResponseDto.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoard.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java
- 특정 게시글 조회 기능 구현
- 조회수 기능 구현
- 쿠키 활용, 조회수 중복 방지
- 조회수 증가 시 Auditing 수정 시간 변동되는 문제 발생, 추후 논의
=> 자유게시글 조회수 기능 관련 PR입니다.

src/main/frontend/src/App.tsx, src/main/frontend/src/components/data/PostingData.tsx, src/main/frontend/src/components/data/ReplyData.ts, src/main/frontend/src/components/layout/ViewReply.tsx, src/main/frontend/src/components/pages/Board/Free/BoardMain.tsx, src/main/frontend/src/components/pages/Board/Free/ViewPosting.tsx, src/main/frontend/src/model/reply.ts
BoardMain의 props mockup데이터로 변경
=> Feature/#1 free board UI

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardDto.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/repository/FreeBoardRepository.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java
프론트 코드에 설정 되어있는것이 있어서 
일단 미리 올립니다!
=> 자유게시판 목록 조회

src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java, src/main/java/com/hansung/hansungcommunity/dto/QnaReplyDto.java, src/main/java/com/hansung/hansungcommunity/entity/QnaReply.java, src/main/java/com/hansung/hansungcommunity/repository/QnaReplyRepository.java, src/main/java/com/hansung/hansungcommunity/service/QnaReplyService.java
- 댓글 생성 기능 구현
- 대댓글 생성 기능 구현
- 댓글 조회 기능 구현(임시)
=> Q&A 게시판 댓글 기능 추가 PR입니다.

src/main/frontend/src/components/layout/Navbar.tsx
- NavLink에서 Button으로 변경
- MenuItem 수직 구현 미해결
=> FEAT : #42 - 드롭다운 메뉴 구현

src/main/frontend/src/components/layout/MostViewedPost.tsx, src/main/frontend/src/components/pages/Board/QnABoard.tsx, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/dto/MostViewedQnaBoardsDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaListResponseDto.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java
- QnaBoard와 QnaReply 연관관계 매핑
- 조회 관련 DTO 생성
- 조회 API 구현
- 데이터 연동 로직 구현
=> Q&A 게시판 목록 조회 연동 관련 PR입니다.

src/main/frontend/src/App.tsx, src/main/frontend/src/components/layout/MostViewedPost.tsx, src/main/frontend/src/components/pages/Board/QnABoard.tsx, src/main/frontend/src/components/pages/Board/QnADetails.tsx
- Q&A 게시판에서 해당 게시물 클릭 시, 출력될 UI 구현
- 상세보기 라우팅 처리 및 페이지 이동 구현
- 언어 이미지 처리 안 된 상태
=> FEAT : #53 - Q&A 상세보기 구현

src/main/frontend/src/components/pages/Board/Free/ViewPosting.tsx
=> Feature/#37 free board detail UI

build.gradle, src/main/java/com/hansung/hansungcommunity/config/ResourceServerConfig.java
=> 리소스 서버 설정 

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java
=> 조회수 기능 수정 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/config/CustomJwtAuthenticationTokenConverter.java, src/main/java/com/hansung/hansungcommunity/config/SecurityConfig.java, src/main/java/com/hansung/hansungcommunity/config/WebMvcConfig.java, src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/FileDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardDetailsDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardResponseDto.java, src/main/java/com/hansung/hansungcommunity/dto/MostViewedQnaBoardsDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardDetailsDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardResponseDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaListResponseDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaReplyDto.java, src/main/java/com/hansung/hansungcommunity/dto/UserDto.java, src/main/java/com/hansung/hansungcommunity/dto/UserRequestDto.java, src/main/java/com/hansung/hansungcommunity/entity/FileEntity.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/entity/QnaReply.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/repository/FreeBoardRepository.java, src/main/java/com/hansung/hansungcommunity/repository/UserRepository.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java
- 불필요한 Import 제거
- 불필요한 메소드 제거
- 불필요한 주석 제거
=> 코드 리팩토링 PR입니다.

src/main/java/com/hansung/hansungcommunity/HansungCommunityApplication.java, src/main/java/com/hansung/hansungcommunity/auth/CustomAuthentication.java, src/main/java/com/hansung/hansungcommunity/config/CustomJwtAuthenticationTokenConverter.java, src/main/java/com/hansung/hansungcommunity/config/SecurityConfig.java, src/main/java/com/hansung/hansungcommunity/repository/UserRepository.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java
- JwtAuthenticationConverter 커스텀
- Authentication 객체로 Convert 할 때, DB에 있는 User 인 경우 CustomAuthentication 으로 변환하고 'ROLE_USER' 권한 부여
- 내부에 User 정보를 담고 있는 CustomAuthentication 구현
- 부여된 권한으로 부가 정보 입력 여부 확인
=> 부가 정보 입력 여부 확인 기능 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardDetailsDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardResponseDto.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java
하단에 나열된 기능들에 User 연동
- 메인 페이지 자유 게시글 조회
- 자유 게시글 목록 조회
- 자유 게시글 상세 조회
- 자유 게시글 작성
=> 자유게시판 User 연동 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/dto/MostViewedQnaBoardsDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardDetailsDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/QnaBoardResponseDto.java
하단에 나열된 기능들에 User 연동 작업 및 API 스펙을 수정했습니다.
- 메인 페이지 Q&A 게시글 조회
- Q&A 게시글 목록 조회
- Q&A 게시글 상세 조회
- Q&A 게시글 작성
=> Q&A게시판 User 연동 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java
=> QnaReply코드 수정 

src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/UserInfoDto.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java
=> 메인페이지 유저 정보 받기

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardBookmarkDto.java, src/main/java/com/hansung/hansungcommunity/dto/FreeBoardDto.java, src/main/java/com/hansung/hansungcommunity/dto/UserDto.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoardBookmark.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/repository/FreeBoardBookmarkRepository.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardBookmarkService.java
- 다대다 풀어서 구현
> FreeBoard  :   Bookmark   :  User
=> 자유게시판 북마크 로직 구현

src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java, src/main/java/com/hansung/hansungcommunity/entity/QnaReply.java, src/main/java/com/hansung/hansungcommunity/repository/QnaReplyRepository.java, src/main/java/com/hansung/hansungcommunity/service/QnaReplyService.java
- 현재 Q&A 댓글 쪽  프론트단이 없어서 로직만 구현하였습니다. (테스트완료)
=> Q&A 게시판 댓글 채택 로직

src/main/java/com/hansung/hansungcommunity/controller/FreeReplyController.java, src/main/java/com/hansung/hansungcommunity/entity/FreeReply.java, src/main/java/com/hansung/hansungcommunity/service/FreeReplyService.java
=> 자유게시판 댓글 수정,삭제

src/main/java/com/hansung/hansungcommunity/dto/free/FreeReplyDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserInfoDto.java, src/main/java/com/hansung/hansungcommunity/repository/FreeReplyRepository.java, src/main/java/com/hansung/hansungcommunity/repository/QnaReplyRepository.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java
- free,qna repository : 마이페이지에서 댓글 숫자 가져오기 위해 코드 추가
=> myPage 연동 로직 추가

src/main/java/com/hansung/hansungcommunity/config/SecurityConfig.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java
협의 내용을 기반으로 Q&A 게시판 API URI 리팩토링을 수행하였습니다.
=> Q&A 게시판 API URI 리팩토링 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java
- 프론트 단에서 해당 접속 유저의 id만 받아오기 위해 api 하나 추가
=> 자유게시판 버튼 연동

src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardDetailsDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardMainDto.java, src/main/java/com/hansung/hansungcommunity/dto/qna/QnaBoardDetailsDto.java, src/main/java/com/hansung/hansungcommunity/dto/qna/QnaBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/qna/QnaBoardMainDto.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/FreeReply.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoardBookmark.java, src/main/java/com/hansung/hansungcommunity/repository/FreeReplyRepository.java, src/main/java/com/hansung/hansungcommunity/service/FreeReplyService.java
- 자유, Q&A게시글과  북마크, 댓글 간 연관관계 매핑
- 불필요 필드 제거(북마크 수, 신고 수)
- 관련 DTO 수정
- 관련 클래스 리팩토링
=> 게시글 엔티티 연관관계 매핑 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java, src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserRankDto.java, src/main/java/com/hansung/hansungcommunity/entity/Adopt.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/repository/AdoptRepository.java, src/main/java/com/hansung/hansungcommunity/service/QnaReplyService.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java
- Adopt 엔티티를 만들어 연관관계를 통해 조회 하였습니다
1. QnaReplyService : 채택을 할 때, 여기서추가로  채택된 Adopt 테이블 등록
2.  UserService : 유저 순위 반환
=> Qna 채택 및 메인페이지 유저 순위 로직

src/main/java/com/hansung/hansungcommunity/dto/user/UserInfoDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserRequestDto.java, src/main/java/com/hansung/hansungcommunity/entity/Skill.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/repository/SkillRepository.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java, src/main/resources/data.sql
- 관심 기술 엔티티(Skill) 구현
- User 엔티티와 다대다 연관관계 설정
- 회원가입 로직에 관심 기술 관련된 로직 추가
- 기존 UserRequestDto에 관심 기술 필드 추가 및 관련 로직 구현
- 관심 기술 초기값 저장을 위해 data.sql 수정
=> 유저 관심 기술 저장 기능 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardUpdateDto.java, src/main/java/com/hansung/hansungcommunity/dto/qna/QnaBoardUpdateDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardUpdateDto.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/entity/RecruitBoard.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
자유, Q&A, 구인 게시글에 대해 다음의 작업을 수행했습니다.
- Data Buffering 용도의 기존 게시글 정보 API 구현
- 관련 DTO 생성
- 관련 비즈니스 로직 작성
=> 게시글 수정, 삭제 기능 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/user/SimpleUserInfoDto.java
=> 유저 정보 API 분리 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardBookmarkService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardBookmarkService.java
-  등록 시 dto를 보내도록 변경 
-  취소 시 상태 200으로만 확인하므로 void null값 전해주도록 변경
=> 자유/qna 게시판 북마크 리팩토링

src/main/java/com/hansung/hansungcommunity/entity/Board.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/entity/RecruitBoard.java
- Mypage 로직 구현에 편리함을 위해 Board 엔티티에  User 엔티티를 추가하였습니다.
=> Board 엔티티 User 컬럼 추가

src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/ApplicantDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardDetailDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardUpdateDto.java, src/main/java/com/hansung/hansungcommunity/entity/Party.java, src/main/java/com/hansung/hansungcommunity/entity/RecruitBoard.java, src/main/java/com/hansung/hansungcommunity/repository/PartyRepository.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
아래와 같은 작업을 수행했습니다.
- 모집 완료 처리와 신청자 목록, 신청 인원 수를 응답하는 API 구현
- 관련 비즈니스 로직 구현 
- 신청자 정보를 담는 DTO 생성
- 모집 인원 수 로직 수정
=> 구인 게시판 신청 기능 관련 API 구현 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/dto/BoardMainDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserActivityDto.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java
아래와 같은 작업을 수행했습니다.
- 게시글 작성 시 응답 데이터를 생성된 게시글의 ID로 통일
- board 타입을 변환해주는 메소드 일부 수정
=> 게시글 생성 API 수정 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/MyPageController.java, src/main/java/com/hansung/hansungcommunity/controller/SummaryContoller.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserSummaryDto.java, src/main/java/com/hansung/hansungcommunity/entity/Summary.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/repository/SummaryRepository.java, src/main/java/com/hansung/hansungcommunity/service/SummaryService.java
=> 공부기록 API 구현

src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
- 신청 취소 API 구현
- 신청 여부 확인 API 구현
- 게시글 작성자는 신청 불가하도록 검증 로직 추가
=> 구인 게시글 신청 취소, 신청 여부 확인 API 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/dto/ImageDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/qna/QnaBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardListDto.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
- 각 게시판 dto에 추출한 이미지 ImageDto 추가
=> 게시판 목록 이미지 추출

src/main/java/com/hansung/hansungcommunity/controller/MyPageController.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserUpdateDto.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/service/MyPageService.java
- 유저 정보(자기 소개, 관심 기술)을 수정하는 API 구현
- 관련 DTO 생성
- 관련 비즈니스 로직 구현
=> 유저 정보 수정 API 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/NoticeController.java, src/main/java/com/hansung/hansungcommunity/dto/NoticeBoardDto.java, src/main/java/com/hansung/hansungcommunity/entity/NoticeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/repository/NoticeRepository.java, src/main/java/com/hansung/hansungcommunity/service/NoticeService.java
=> 공지사항 API 구현 (초안)

src/main/java/com/hansung/hansungcommunity/config/CustomJwtAuthenticationTokenConverter.java, src/main/java/com/hansung/hansungcommunity/config/SecurityConfig.java, src/main/java/com/hansung/hansungcommunity/controller/AdminContoller.java, src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/AdminBoardDto.java, src/main/java/com/hansung/hansungcommunity/dto/AdminUserDto.java, src/main/java/com/hansung/hansungcommunity/repository/BoardRepository.java, src/main/java/com/hansung/hansungcommunity/service/AdminService.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java
관리자 페이지에서
- 게시글 조회, 삭제
- 유저 조회, 삭제
=> 관리자 기능 API 구현

build.gradle, src/main/java/com/hansung/hansungcommunity/config/FireBaseInitializer.java, src/main/java/com/hansung/hansungcommunity/config/SecurityConfig.java, src/main/java/com/hansung/hansungcommunity/controller/FirebaseContoller.java, src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/dto/FileDto.java, src/main/java/com/hansung/hansungcommunity/entity/FileEntity.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/RecruitBoard.java, src/main/java/com/hansung/hansungcommunity/service/FileService.java, src/main/java/com/hansung/hansungcommunity/service/FireBaseService.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java, src/main/resources/serviceAccountKey.json
=> firebase 이미지 API 연동

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/repository/FreeBoardRepository.java, src/main/java/com/hansung/hansungcommunity/repository/QnaBoardRepository.java, src/main/java/com/hansung/hansungcommunity/repository/RecruitBoardRepository.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
각 게시판 별 아래의 작업을 수행했습니다.
- 기존 게시판 목록 조회 API의 비즈니스 로직에 북마크 수 정렬 기능 보완
=> 각 게시판 목록 조회 API 비즈니스 로직 보완 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/FirebaseContoller.java, src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/dto/FileDto.java, src/main/java/com/hansung/hansungcommunity/dto/FileRequestDto.java, src/main/java/com/hansung/hansungcommunity/repository/FileRepository.java, src/main/java/com/hansung/hansungcommunity/service/FileService.java
- 삭제 (0)
- 다운로드 (0)
- 이미지 orininalName 전송(0)
=> 상세보기 페이지 이미지 API 구현

src/main/java/com/hansung/hansungcommunity/controller/GlobalExceptionHandler.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserUpdateDto.java, src/main/java/com/hansung/hansungcommunity/entity/User.java, src/main/java/com/hansung/hansungcommunity/exception/DuplicateNicknameException.java, src/main/java/com/hansung/hansungcommunity/repository/UserRepository.java, src/main/java/com/hansung/hansungcommunity/service/MyPageService.java
아래와 같은 작업을 수행했습니다.
- 닉네임 변경이 가능하도록 닉네임 필드 추가
- 수정 요청 닉네임이 중복되는 경우 응답 바디에 에러 메시지 포함하여 400 에러 응답
=> 유저 정보 수정 API 보완 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/MyPageController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitReplyController.java, src/main/java/com/hansung/hansungcommunity/controller/SummaryController.java, src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardRequestDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitReplyDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserCheckNicknameDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserRequestDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserSummaryDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserUpdateDto.java
- 닉네임, 자기 소개, 공부 요약 등 유저와 관련된 필드에 검증 로직 추가
- 제목, 내용 등 구인 게시판과 관련된 필드에 검증 로직 추가
=> 유저, 구인 게시판 검증 로직 관련 PR입니다.

src/main/java/com/hansung/hansungcommunity/controller/FirebaseController.java, src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/NoticeController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/dto/FileDto.java, src/main/java/com/hansung/hansungcommunity/entity/FileEntity.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/entity/RecruitBoard.java, src/main/java/com/hansung/hansungcommunity/repository/FileRepository.java, src/main/java/com/hansung/hansungcommunity/service/FileService.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/NoticeService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
=> File API 로직 추가

src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/FreeBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/FreeReplyController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardApplyRequestDto.java, src/main/java/com/hansung/hansungcommunity/service/BookmarkService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java, src/main/java/com/hansung/hansungcommunity/service/UserService.java
- 불필요한 객체 생성 방지를 위해 박싱 타입을 기본 타입으로 대체
=> REFACTOR : #220 - 박싱 타입을 기본 타입으로 대체

src/main/java/com/hansung/hansungcommunity/ImageUtils.java
- ImageUtils 클래스의 인스턴스화 방지를 위해 기본 생성자의 접근 제한자를 private으로 제한
=> REFACTOR : #218 - ImageUtils 클래스 인스턴스화 방지

src/main/java/com/hansung/hansungcommunity/controller/NoticeBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/NoticeController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java, src/main/java/com/hansung/hansungcommunity/entity/QnaReply.java, src/main/java/com/hansung/hansungcommunity/service/QnaReplyService.java
=> REFACTOR : #222 - 박싱 타입 리팩토링

src/main/java/com/hansung/hansungcommunity/dto/BoardMainDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardDetailsDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardMainDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardRequestDto.java, src/main/java/com/hansung/hansungcommunity/dto/free/FreeBoardUpdateDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/ApplicantDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardDetailDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardListDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardMainDto.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardUpdateDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/SimpleUserInfoDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserActivityDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserInfoDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserRankDto.java, src/main/java/com/hansung/hansungcommunity/dto/user/UserReplyDto.java
- DTO 클래스의  필드 변경 가능성 최소화 및 불변성 보장을 위해 필드에 final 키워드 적용
=> REFACTOR : #224 - DTO 클래스 필드에 final 키워드 적용

src/main/java/com/hansung/hansungcommunity/ImageUtils.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
- FreeBoardService/QnaBoardService의 목록 페이지에 띄울 이미지 resize url 설정을 위한 로직을 ImageUtils 클래스에  메서드로 넣어 공통 사용.
- RecruitBoard에서는 resize 할 필요가 없기에 resize하는 메서드 제거.
=> REFACTOR : #234 - ImageUtils 클래스 코드 추가 (ImageResize 통합 메서드)

src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java, src/main/java/com/hansung/hansungcommunity/entity/QnaReply.java, src/main/java/com/hansung/hansungcommunity/repository/AdoptRepository.java, src/main/java/com/hansung/hansungcommunity/repository/QnaReplyRepository.java, src/main/java/com/hansung/hansungcommunity/repository/ReplyRepository.java, src/main/java/com/hansung/hansungcommunity/service/QnaReplyService.java
- QnaReply entity의 adopt 필드 제거하여 adopt 필드를 사용하여 댓글 채택/취소/삭제 등 관련 코드를 Adopt 테이블을 사용한 코드로 로직 변경
- etc.. . : QnaReplyController의 adopt 메서드에서 사용하지 않는 Authenication 매개변수가 있어 제거.
=> REFACTOR : #237 - QnaReply 리팩토링

src/main/java/com/hansung/hansungcommunity/dto/notice/NoticeBoardDto.java, src/main/java/com/hansung/hansungcommunity/entity/Board.java, src/main/java/com/hansung/hansungcommunity/entity/FreeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/NoticeBoard.java, src/main/java/com/hansung/hansungcommunity/entity/QnaBoard.java, src/main/java/com/hansung/hansungcommunity/entity/RecruitBoard.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/NoticeService.java, src/main/java/com/hansung/hansungcommunity/service/QnaBoardService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
- 불필요한 메서드 제거
- 중복 코드 메서드로 추출
- 중복 정의된 id 필드 제거
- 일부 final 키워드 추가
- 불필요한 연관관계 필드 제거
=> REFACTOR : #235 - Board 클래스 및 하위 클래스 리팩토링

src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/dto/ApplicationStatus.java, src/main/java/com/hansung/hansungcommunity/dto/recruit/RecruitBoardApplyRequestDto.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java
- 신청 정보(미신청, 신청_미승인, 신청_승인)를 담는 Enum 클래스 생성
- 신청 여부를 확인하는 API의 반환 타입을 해당 Enum 클래스로 변경
- 신청 기능의 정상 동작을 위해 신청 정보가 매핑되는 DTO 클래스의 필드 타입을 박싱 타입으로 변경
=> REFACTOR : #240 - 신청 여부 확인 API 수정 및 신청 정보 DTO 수정

src/main/java/com/hansung/hansungcommunity/controller/AdminController.java, src/main/java/com/hansung/hansungcommunity/controller/FirebaseController.java, src/main/java/com/hansung/hansungcommunity/controller/FreeBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/FreeBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/FreeReplyController.java, src/main/java/com/hansung/hansungcommunity/controller/MyPageController.java, src/main/java/com/hansung/hansungcommunity/controller/NoticeBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/NoticeController.java, src/main/java/com/hansung/hansungcommunity/controller/NoticeReplyController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardApiController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/QnaReplyController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardBookmarkController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitBoardController.java, src/main/java/com/hansung/hansungcommunity/controller/RecruitReplyController.java, src/main/java/com/hansung/hansungcommunity/controller/UserApiController.java, src/main/java/com/hansung/hansungcommunity/repository/ReplyRepository.java, src/main/java/com/hansung/hansungcommunity/service/AdminService.java, src/main/java/com/hansung/hansungcommunity/service/BookmarkService.java, src/main/java/com/hansung/hansungcommunity/service/FileService.java, src/main/java/com/hansung/hansungcommunity/service/FreeBoardService.java, src/main/java/com/hansung/hansungcommunity/service/NoticeService.java, src/main/java/com/hansung/hansungcommunity/service/QnaReplyService.java, src/main/java/com/hansung/hansungcommunity/service/RecruitBoardService.java, src/main/java/com/hansung/hansungcommunity/service/ReplyService.java
- 메서드의 이름을 [행위(동사)] + [대상] 으로 명명.
=> REFACTOR : #242-메서드 네이밍 리팩토링
